apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghes-schedule-scanner.fullname" . }}-exclude
  labels:
    {{- include "ghes-schedule-scanner.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  exclude-repos.txt: |-
    {{- range .Values.excludedRepositoriesList }}
    {{ . | indent 4 }}
    {{- end }}