apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "ghes-schedule-scanner.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.schedule | quote }}
  timeZone: {{ .Values.timeZone | default "Etc/UTC" }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "ghes-schedule-scanner.labels" . | nindent 12 }}
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ include "ghes-schedule-scanner.imageTag" . }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: GITHUB_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: GITHUB_BASE_URL
            - name: GITHUB_ORGANIZATION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: GITHUB_ORGANIZATION
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: LOG_LEVEL
            - name: REQUEST_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: REQUEST_TIMEOUT
            - name: CONCURRENT_SCANS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: CONCURRENT_SCANS
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: GITHUB_TOKEN
            - name: SLACK_BOT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: SLACK_BOT_TOKEN
            - name: SLACK_CHANNEL_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: SLACK_CHANNEL_ID
            - name: SLACK_CANVAS_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-config
                  key: SLACK_CANVAS_ID
            resources:
              limits:
                cpu: {{ .Values.resources.limits.cpu }}
                memory: {{ .Values.resources.limits.memory }}
              requests:
                cpu: {{ .Values.resources.requests.cpu }}
                memory: {{ .Values.resources.requests.memory }}
          restartPolicy: {{ .Values.restartPolicy }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.topologySpreadConstraints }}
          topologySpreadConstraints:
            {{- toYaml . | nindent 12 }}
          {{- end }}
