# -- Container image configuration
image:
  # -- Container image repository
  # This value is used to specify the container image repository.
  repository: ghcr.io/younsl/ghes-schedule-scanner
  # -- Image pull policy (Available values: Always, IfNotPresent, Never)
  pullPolicy: IfNotPresent
  # -- Container image tag (If not set, will use Chart's appVersion by default.)
  tag: null

# -- CronJob schedule in Cron format (UTC)
# This value is used to configure the schedule for the CronJob.
# Cron expression details:
# minute (0-59), hour (0-23), day of month (1-31), month (1-12), day of week (0-7), `*` means all
schedule: "0 1 * * *"

# -- TTL in seconds for finished jobs
# This value is used to delete finished jobs after a certain period of time.
# This helps to reduce the number of old job pods that are kept in the cluster.
ttlSecondsAfterFinished: 3600

# -- Number of successful jobs to keep in history
# This value is used to limit the number of successful jobs
successfulJobsHistoryLimit: 3

# -- Number of failed jobs to keep in history
# This value is used to limit the number of failed jobs
failedJobsHistoryLimit: 1

# -- CronJob annotations
# annotations are used to configure additional CronJob settings
annotations: {}

# -- Pod annotations
# annotations are used to configure additional pod settings
podAnnotations: {}
  # linkerd.io/inject: disabled
  # karpenter.sh/do-not-disrupt: true

# -- ConfigMap data containing application configuration
configMap:
  data:
    # -- GitHub Enterprise organization name
    # Organization name is used to scan all repositories for the given organization
    GITHUB_ORGANIZATION: "example-org"
    # -- GitHub Enterprise base URL
    # The API endpoint will be automatically appended with '/api/v3'
    # For example: https://github.example.com/api/v3
    GITHUB_BASE_URL: "https://github.example.com"
    # -- Application log level
    LOG_LEVEL: "INFO"
    # -- HTTP request timeout in seconds
    REQUEST_TIMEOUT: "30"
    # -- Number of concurrent repository scans
    # This value is used to limit the number of concurrent goroutines
    # that are scanning repositories.
    # Recommended CONCURRENT_SCANS value depends on several factors:
    # - GitHub API rate limits
    # - GitHub API response time (latency)
    # - Network conditions between your cluster and GitHub Enterprise
    # Typical values range from 10-50, but can be higher if needed.
    CONCURRENT_SCANS: "10"

# -- Name of the secret containing sensitive data
# This secret is used to store the GitHub access token with permissions
# to scan repositories.
secretName: "ghes-schedule-scanner-secret"

# -- Container resource requirements
resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"

# -- Node selector for pod assignment
# nodeSelector is used to configure additional pod settings
nodeSelector: {}
# Example:
#   kubernetes.io/os: linux
#   node-type: worker

# -- Pod tolerations
# tolerations are used to configure additional pod settings
tolerations: []
# Example:
# - key: "node-role"
#   operator: "Equal"
#   value: "worker"
#   effect: "NoSchedule"

# -- Pod affinity settings
# affinity is used to configure additional pod settings
affinity: {}
# Example:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/e2e-az-name
#           operator: In
#           values:
#           - e2e-az1
#           - e2e-az2

# -- Pod scheduling constraints for spreading pods across nodes or zones
# topologySpreadConstraints are used to configure additional pod settings
topologySpreadConstraints: []
# Example:
# - maxSkew: 1
#   topologyKey: kubernetes.io/hostname
#   whenUnsatisfiable: ScheduleAnyway
#   labelSelector:
#     matchLabels:
#       app.kubernetes.io/name: ghes-schedule-scanner
