apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "ghes-schedule-scanner.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  GITHUB_BASE_URL: {{ .Values.configMap.data.GITHUB_BASE_URL | quote }}
  GITHUB_ORGANIZATION: {{ .Values.configMap.data.GITHUB_ORGANIZATION | quote }}
  LOG_LEVEL: {{ .Values.configMap.data.LOG_LEVEL | quote }}
  REQUEST_TIMEOUT: {{ .Values.configMap.data.REQUEST_TIMEOUT | quote }}
  CONCURRENT_SCANS: {{ .Values.configMap.data.CONCURRENT_SCANS | quote }}